apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"a":"b","app":"test-app","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"test-app","app.kubernetes.io/version":"test","c":"d"},"name":"test-app","namespace":"foobar"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"test-app"}},"template":{"metadata":{"labels":{"app":"test-app"}},"spec":{"containers":[{"image":"gcr.io/cloud-spinnaker-artifacts/gate:1.7.2-20190425164041","name":"test-app"}]}}}}
  creationTimestamp: 2019-06-06T17:26:36Z
  generation: 2
  labels:
    a: b
    app: test-app
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: test-app
    app.kubernetes.io/version: test
    c: d
  name: test-app
  namespace: foobar
  resourceVersion: "4249190"
  selfLink: /apis/extensions/v1beta1/namespaces/foobar/deployments/test-app
  uid: 3cbea91a-8880-11e9-8840-42010a8e00dc
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app@sha256:1c7c73c049dafddcc82f61bd50c70a8061c301bb63065fca6cff1f1ef10b9afc
        imagePullPolicy: IfNotPresent
        name: test-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2019-06-01T14:40:02Z
    lastUpdateTime: 2019-06-02T14:12:13Z
    message: ReplicaSet "test-app-d7d58977d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2019-06-06T17:26:36Z
    lastUpdateTime: 2019-06-06T17:26:36Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
